repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: ^{{cookiecutter.project_slug}}/
    -   id: end-of-file-fixer
        exclude: ^{{cookiecutter.project_slug}}/
    -   id: trailing-whitespace
        exclude: ^{{cookiecutter.project_slug}}/
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: ^{{cookiecutter.project_slug}}/
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
